-- Run after schema.sql
-- Passwords are bcrypt-hashed values generated by backend/scripts/generate_hashes.mjs

insert into public.teams (team_id, password_hash, points, current_round, is_admin)
values
  ('TEAM01', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM02', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM03', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM04', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM05', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM06', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM07', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM08', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM09', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM10', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM11', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM12', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM13', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM14', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM15', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM16', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM17', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM18', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM19', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM20', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM21', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM22', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM23', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM24', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM25', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM26', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM27', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM28', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM29', '$2a$10$REPLACE_ME', 0, 0, false),
  ('TEAM30', '$2a$10$REPLACE_ME', 0, 0, false),
  ('ADMIN01', '$2a$10$REPLACE_ME', 0, 0, true)
on conflict (team_id) do nothing;

insert into public.game_state (team_id)
select t.id
from public.teams t
left join public.game_state gs on gs.team_id = t.id
where gs.team_id is null;
