-- Run after schema.sql
-- Passwords are bcrypt-hashed values generated by backend/scripts/seedCredentials.mjs
-- This file is a template; use the seed script for actual seeding.

-- Example manual insert (replace $2a$10$REPLACE_ME with actual hashes):
INSERT INTO teams (id, team_id, password_hash, points, current_round, is_admin)
VALUES
  (UUID(), 'TEAM01', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM02', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM03', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM04', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM05', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM06', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM07', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM08', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM09', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM10', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM11', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM12', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM13', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM14', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM15', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM16', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM17', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM18', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM19', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM20', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM21', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM22', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM23', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM24', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM25', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM26', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM27', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM28', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM29', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'TEAM30', '$2a$10$REPLACE_ME', 0, 0, 0),
  (UUID(), 'ADMIN01', '$2a$10$REPLACE_ME', 0, 0, 1)
ON DUPLICATE KEY UPDATE team_id = team_id;

-- Insert game_state for each team that doesn't have one
INSERT INTO game_state (team_id)
SELECT t.id
FROM teams t
LEFT JOIN game_state gs ON gs.team_id = t.id
WHERE gs.team_id IS NULL;
