export const AUCTION_CARDS = [
  { id: 'SC01', name: 'STRATEGIC TIMEOUT', type: 'negative', effect_type: 'freeze', value: 420, target_type: 'other', duration: 420, min_value: 5000, description: 'FREEZE FOR 7 MINUTE' },
  { id: 'SC02', name: 'Third Umpire', type: 'positive', effect_type: 'hint', value: 1, target_type: 'self', duration: null, min_value: 5000, description: 'Get a hint directly from organizers.' },
  { id: 'SC03', name: 'No Ball', type: 'neutral', effect_type: 'revoke_card', value: 1, target_type: 'other', duration: null, min_value: 5000, description: 'can revoke any other team’s supercard' },
  { id: 'SC04', name: 'Wide ball', type: 'positive', effect_type: 'random_answer', value: 1, target_type: 'self', duration: null, min_value: 5000, description: 'one random answer but will not know of which' },
  { id: 'SC05', name: 'Shield', type: 'positive', effect_type: 'protection', value: 1, target_type: 'self', duration: null, min_value: 8000, description: 'One super Card used on you will be dismissed' },
  { id: 'SC06', name: 'Pitch Report', type: 'positive', effect_type: 'reveal_technique', value: 1, target_type: 'self', duration: null, min_value: 7000, description: 'Reveal the technique used (LSB, metadata, etc.)' },
  { id: 'SC07', name: 'UltraEdge', type: 'positive', effect_type: 'reveal_data', value: 1, target_type: 'self', duration: null, min_value: 5000, description: 'Reveal a small portion of hidden data.' },
  { id: 'SC08', name: 'Hatrick', type: 'positive', effect_type: 'no_cooldown', value: 3, target_type: 'self', duration: null, min_value: 2000, description: 'Cooldown will be removed for 3 ans' },
  { id: 'SC09', name: 'Length ball', type: 'positive', effect_type: 'short_path', value: 1, target_type: 'self', duration: null, min_value: 7000, description: 'short path of 4th round' },
  { id: 'SC10', name: 'Ball Tracking', type: 'positive', effect_type: 'reveal_qr', value: 1, target_type: 'self', duration: null, min_value: 7000, description: 'Right QR will be showed to you' },
  { id: 'SC11', name: 'Cover Drive', type: 'positive', effect_type: 'reveal_format', value: 1, target_type: 'self', duration: null, min_value: 5000, description: 'Reveal answer format (word/number/phrase)' },
  { id: 'SC12', name: 'Shield (2)', type: 'positive', effect_type: 'protection', value: 1, target_type: 'self', duration: null, min_value: 8000, description: 'One super Card used on you will be dismissed' },
  { id: 'SC13', name: 'Helicopter Shot', type: 'positive', effect_type: 'select_card', value: 1, target_type: 'self', duration: null, min_value: 9000, description: 'Select any of the given card' },
  { id: 'SC14', name: 'DRS', type: 'positive', effect_type: 'restore_card', value: 1, target_type: 'self', duration: null, min_value: 8000, description: 'you can take any of the card that is used earlier' },
  { id: 'SC15', name: 'Impact player', type: 'neutral', effect_type: 'impact_player', value: 1, target_type: 'other', duration: null, min_value: 4000, description: 'The team will pick any of one person from another team and the team will decide what he has to do' },
  { id: 'SC16', name: 'Purple Cap', type: 'negative', effect_type: 'riddle_pause', value: 1, target_type: 'other', duration: null, min_value: 5000, description: 'The team will choose one team which have to solve one riddle till then they will be paused' },
  { id: 'SC17', name: 'Shield (3)', type: 'positive', effect_type: 'protection', value: 1, target_type: 'self', duration: null, min_value: 8000, description: 'One super Card used on you will be dismissed' },
  { id: 'SC18', name: 'King Kohli Mode', type: 'positive', effect_type: 'direct_answer', value: 1, target_type: 'self', duration: null, min_value: 9000, description: 'Give directly the answer for one round' },
  { id: 'SC19', name: 'Grass is Wet', type: 'neutral', effect_type: 'global_freeze', value: 120, target_type: 'all', duration: 120, min_value: 6000, description: 'For 2 minutes everyone will be refrained from submitting the answer they can’t submit the answer except the team who used it.' },
  { id: 'SC20', name: 'Keiron Pollard', type: 'negative', effect_type: 'delete_card', value: 1, target_type: 'other', duration: null, min_value: 9000, description: 'This will delete anyone team’s one supercard' },
  { id: 'SC21', name: 'Cooldown Surge', type: 'negative', effect_type: 'cooldown_increase', value: 60, target_type: 'other', duration: null, min_value: 4000, description: 'Increase the targeted team’s answer cooldown time by +1 minute for their next attempts.' },
];
